{% set name = "delegator.py" %}
{% set version = "0.0.13" %}
{% set sha256 = "495e11ada66648650171a6c9a188df4eb050b235abff8771f41ee8a064eb9ded" %}

package:
  name: delegator
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pexpect >=4.1.0

test:
  imports:
    - delegator

about:
  home: https://github.com/kennethreitz/delegator.py
  license: MIT
  license_family: MIT
  summary: Subprocesses for Humans 2.0.
  description: |
      Delegator.py is a simple library for dealing with subprocesses, inspired
      by both envoy and pexpect (in fact, it depends on it!).
      This module features two main functions delegator.run() and
      delegator.chain(). One runs commands, blocking or non-blocking, and the other
      runs a chain of commands, seperated by the standard unix pipe operator "|"

extra:
  recipe-maintainers:
    - ericdill
