travis:
  secure:
    BINSTAR_TOKEN: shrKv4P2y9V2zyjZQxT9dzp32LsOogrF37Q8np1vI2qWXp4UWv188ksXNTWv7HCkKg5BEK4IKF5PZ3kmsvnBUkIISobkx3a4bw5Oc4WjwYOXhi+Upo8KxAZ1RwSnV+OcjutQE97WnKZtifDGLdkXz1IHkp837tWNoBck20Ysr+ehHg+s0mZui3mDJ1iXu0NmNterJuf7tf1hyPslz0sFtW+EboGTmJAKcQssqQjP/9s6vYGuWM67RjaIynThAlYICEbAvNhJHQO2YLyGlmGYst+RwDRF4jLQQzcfy+ckkqSWnx7He+cBlyGlAMXSjQ3gzA8oLfeVq7HcTqy9qnAp//MgNbWrPK8JmuU9QUY6fFPBqsO/pzGHxvLopk2B7h/TS1hRk+t1GlWM+L/Pc5z3lIPAzehTDDMFylxTN0rHSRtt8YeE2zIQC6ddNRrEHmn0nh2QEJpZQ1EW2WfmKQ0rY6yX8qzSiHqbayPt8pszBZIPQE7VGY0OiCNtJiN3kR9y6kk+BJH84nOnjUHc9+joAQp2HOEtVQ6q2jH/DnZpB4YR7E815tSqa8rSrodUJtfqJVmAXiOzd4MvJwyED6CkH9Zoqgqq/vg6ciP+Ct2Tve4+Ht+O51W1tPSeAQ1zohtZHvXZrUf1HW8nB47wOn+guK96eb547RnnD8/ACISRxeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
