travis:
  secure:
    BINSTAR_TOKEN: SM3oNxtBfiJmgxq4YJh7mZdqN9yPmkzJea+bw6Y33zgVeEE4nxtsmd3smzdGS2RFR1kcbw17k/qJXICstewRB6I61fLNtE82mAdFXQAdIlUOarll3YMqE6rAUOrVSS6wHwRuVVq85QuH9601oN4Fgk84v1VSD1AXJS9C4CIK+TpQ2WHzJjBZSZunIkis1zRZS3b8soNALKbT6idmE4A1KpM302wegxicEMdzqLvq8yR1oS4Rynpv4x+Xo2k67tvd8OlbjdlfDz7IYwSS1LVWqG0KqrlsnyYtpfSIdX9e45FwwRZ3RCVTOK0WGxVp4sgdlIybDrJxWtiPcFXhgKmsyL+QSOIvBvQpa9YfC4hm6kouVhqzNHbeka42DBN3HkWX+/7xgxAcQPf+k6m82s2IQ4StPh+D1UX8JH6t5qfp4661c1W2KkEccyW4wUUU2kE7ymKMC5iobdeoGUn/+6uD98hIwwfX4hS6OZuDZoYT5DwkLpT4UIEQRGnCUM5yfL6vu+0ITzpnJp4WlvbEthYFAmvmAzanjrv2EFfH4hzQPrtx3JpIy5xxPLsdNvUq6SHHb4h8gNYrAkjc3zMxxPdqpZtE+RWVPntGObGCErnsP7YJaHE77db/zn68JruNLktvR45LgD8maH2jjf5NLjOu8SLyoPAo18gzwa9GMEeFX7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
